#!/usr/bin/env bash
set -Eeuo pipefail

MODE="${1:-}"
shift || true
PACKAGE="${1:-}"
APP_ROOT="${PULSIA_APP_ROOT:-/almacen}"
APP_SERVICE="pulsia-inventario"; CADDY_SERVICE="pulsia-inventario-caddy"; STAMP="$(date +%Y%m%d_%H%M%S)"; WORKDIR=""; SOURCE_ROOT=""; UPDATE_STARTED=0
info(){ echo "[INFO] $*"; }; ok(){ echo "[OK] $*"; }; warn(){ echo "[AVISO] $*"; }; fail(){ echo "[ERROR] $*" >&2; exit 1; }
usage(){ echo "Uso: $0 <solo-programa|programa-y-bd|estructural> [/ruta/version_nueva.zip|/ruta/carpeta_nueva]"; echo "Destino por defecto: /almacen. Si no existe, se solicita la ruta real."; }
[[ "$MODE" == solo-programa || "$MODE" == programa-y-bd || "$MODE" == estructural ]] || { usage; fail "Modo no válido."; }
[[ ${EUID} -eq 0 ]] || exec sudo -E "$0" "$MODE" "$PACKAGE"
resolve_app_root(){
 [[ -d "$APP_ROOT" && -f "$APP_ROOT/manage.py" ]] && return
 warn "No se ha encontrado PULSIA Almacén en $APP_ROOT."
 [[ -t 0 ]] || fail "Use PULSIA_APP_ROOT=/ruta/almacen."
 while true; do read -r -p "Ruta de la instalación actual de PULSIA Almacén: " candidate; [[ -n "$candidate" ]] || continue; if [[ -d "$candidate" && -f "$candidate/manage.py" && -d "$candidate/inventory" && -d "$candidate/config" ]]; then APP_ROOT="$(cd "$candidate" && pwd)"; break; fi; echo "[AVISO] Ruta no válida."; done
}
resolve_app_root
BACKUP_ROOT="$APP_ROOT/backups/actualizaciones"; BACKUP_DIR="$BACKUP_ROOT/$STAMP"; DB_PATH="$APP_ROOT/data/inventario.sqlite3"; ENV_PATH="$APP_ROOT/.env"; CODE_BACKUP="$BACKUP_DIR/codigo_previo.tar.gz"; DB_BACKUP="$BACKUP_DIR/inventario.sqlite3"; ENV_BACKUP="$BACKUP_DIR/.env"; SYSTEMD_BACKUP="$BACKUP_DIR/systemd"; METADATA_FILE="$BACKUP_DIR/backup_info.txt"
cleanup(){ [[ -n "$WORKDIR" && -d "$WORKDIR" ]] && rm -rf "$WORKDIR" || true; }; trap cleanup EXIT
rollback(){ local rc=$?; trap - ERR; echo "[ERROR] Actualización fallida. Restaurando..." >&2; if [[ $UPDATE_STARTED -eq 1 && -f "$CODE_BACKUP" ]]; then find "$APP_ROOT" -mindepth 1 -maxdepth 1 ! -name '.venv' ! -name '.env' ! -name data ! -name backups ! -name logs ! -name certs -exec rm -rf {} + 2>/dev/null || true; tar -xzf "$CODE_BACKUP" -C "$APP_ROOT" || true; fi; [[ -f "$DB_BACKUP" ]] && cp -a "$DB_BACKUP" "$DB_PATH" || true; [[ -f "$ENV_BACKUP" ]] && cp -a "$ENV_BACKUP" "$ENV_PATH" || true; systemctl daemon-reload >/dev/null 2>&1 || true; systemctl restart "$APP_SERVICE" >/dev/null 2>&1 || true; systemctl restart "$CADDY_SERVICE" >/dev/null 2>&1 || true; exit "$rc"; }; trap rollback ERR
resolve_source(){ local script_project found; script_project="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." 2>/dev/null && pwd || true)"; if [[ -z "$PACKAGE" ]]; then if [[ -n "$script_project" && "$(readlink -f "$script_project")" != "$(readlink -f "$APP_ROOT")" && -f "$script_project/manage.py" ]]; then SOURCE_ROOT="$script_project"; return; fi; [[ -t 0 ]] && read -r -p "Ruta del ZIP o carpeta de la NUEVA versión: " PACKAGE; [[ -n "$PACKAGE" ]] || fail "Falta la nueva versión."; fi; if [[ -d "$PACKAGE" ]]; then [[ -f "$PACKAGE/manage.py" ]] && SOURCE_ROOT="$(cd "$PACKAGE" && pwd)" || { [[ -f "$PACKAGE/almacen/manage.py" ]] && SOURCE_ROOT="$(cd "$PACKAGE/almacen" && pwd)" || fail "Carpeta no válida."; }; elif [[ -f "$PACKAGE" ]]; then command -v unzip >/dev/null || fail "Se necesita unzip."; WORKDIR="$(mktemp -d /tmp/pulsia-update.XXXXXX)"; unzip -q "$PACKAGE" -d "$WORKDIR"; found="$(find "$WORKDIR" -maxdepth 4 -type f -name manage.py -print -quit)"; [[ -n "$found" ]] || fail "ZIP no válido."; SOURCE_ROOT="$(dirname "$found")"; else fail "No existe: $PACKAGE"; fi; [[ "$(readlink -f "$SOURCE_ROOT")" != "$(readlink -f "$APP_ROOT")" ]] || fail "Fuente y destino no pueden ser la misma carpeta."; }
resolve_source; info "Fuente nueva: $SOURCE_ROOT"; info "Instalación actual: $APP_ROOT"
mkdir -p "$BACKUP_DIR"; chmod 0700 "$BACKUP_DIR" || true; systemctl stop "$CADDY_SERVICE" 2>/dev/null || true; systemctl stop "$APP_SERVICE" 2>/dev/null || true
tar -czf "$CODE_BACKUP" -C "$APP_ROOT" --exclude='./.venv' --exclude='./.env' --exclude='./data' --exclude='./backups' --exclude='./logs' --exclude='./certs' --exclude='*/__pycache__' --exclude='*.pyc' .
if [[ -f "$DB_PATH" ]]; then command -v sqlite3 >/dev/null 2>&1 && sqlite3 "$DB_PATH" ".backup '$DB_BACKUP'" || cp -a "$DB_PATH" "$DB_BACKUP"; fi; [[ -f "$ENV_PATH" ]] && cp -a "$ENV_PATH" "$ENV_BACKUP"; mkdir -p "$SYSTEMD_BACKUP"; for unit in /etc/systemd/system/pulsia-inventario.service /etc/systemd/system/pulsia-inventario-caddy.service /etc/systemd/system/pulsia-inventario-storage-admin.service /etc/systemd/system/pulsia-inventario-continuous-backup.service; do [[ -f "$unit" ]] && cp -a "$unit" "$SYSTEMD_BACKUP/"; done; printf 'PULSIA_BACKUP_VERSION=1\nCREATED_AT=%s\nMODE=%s\nAPP_ROOT=%s\nSOURCE_ROOT=%s\n' "$(date --iso-8601=seconds)" "$MODE" "$APP_ROOT" "$SOURCE_ROOT" > "$METADATA_FILE"; ln -sfn "$BACKUP_DIR" "$BACKUP_ROOT/ultimo"; UPDATE_STARTED=1
command -v rsync >/dev/null || fail "Se necesita rsync."; rsync -a --delete --exclude='.venv/' --exclude='.env' --exclude='data/' --exclude='backups/' --exclude='logs/' --exclude='certs/' --exclude='__pycache__/' --exclude='*.pyc' "$SOURCE_ROOT/" "$APP_ROOT/"
APP_USER="$(systemctl show "$APP_SERVICE" -p User --value 2>/dev/null || true)"; [[ -n "$APP_USER" && "$APP_USER" != root ]] || APP_USER="$(stat -c '%U' "$DB_PATH" 2>/dev/null || stat -c '%U' "$APP_ROOT")"; APP_GROUP="$(id -gn "$APP_USER" 2>/dev/null || stat -c '%G' "$APP_ROOT")"; chown -R "$APP_USER:$APP_GROUP" "$APP_ROOT" || true; find "$APP_ROOT/sistema" -type f -name '*.sh' -exec sed -i 's/\r$//' {} + 2>/dev/null || true; find "$APP_ROOT/sistema" -type f -name '*.sh' -exec chmod 0750 {} + 2>/dev/null || true
PYTHON="$APP_ROOT/.venv/bin/python"; PIP="$APP_ROOT/.venv/bin/pip"; [[ -x "$PYTHON" ]] || fail "No existe $PYTHON"; REQ=""; [[ -f "$APP_ROOT/requirements/servidor.txt" ]] && REQ="$APP_ROOT/requirements/servidor.txt"; [[ -z "$REQ" && -f "$APP_ROOT/requirements.txt" ]] && REQ="$APP_ROOT/requirements.txt"; [[ -n "$REQ" && -x "$PIP" ]] && "$PIP" install -r "$REQ"; cd "$APP_ROOT"; [[ "$MODE" != solo-programa ]] && "$PYTHON" manage.py migrate --noinput || warn "Sin migraciones por modo solo-programa."; "$PYTHON" manage.py check; systemctl daemon-reload; systemctl restart "$APP_SERVICE"; systemctl restart "$CADDY_SERVICE"; systemctl is-active --quiet "$APP_SERVICE" || fail "$APP_SERVICE no está activo"; systemctl is-active --quiet "$CADDY_SERVICE" || fail "$CADDY_SERVICE no está activo"; trap - ERR; ok "Actualización completada. Instalación: $APP_ROOT"; echo "Backup: $BACKUP_DIR"
