# Generated by Django 5.2.5 on 2026-08-16 08:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prefix', models.CharField(max_length=12, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('employee_code', models.CharField(blank=True, max_length=40)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=120)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(default='validating', max_length=20)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_imported', models.PositiveIntegerField(default=0)),
                ('rows_incident', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('details', models.TextField()),
                ('kind', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error')], default='warning', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('review', 'En revisión'), ('resolved', 'Resuelta'), ('ignored', 'Ignorada')], db_index=True, default='pending', max_length=12)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('source_sheet', models.CharField(blank=True, max_length=120)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('model_reference', models.CharField(blank=True, max_length=220)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=160)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('assigned', 'Entregado / instalado'), ('testing', 'Pendiente de prueba'), ('incident', 'Incidencia'), ('scrapped', 'Baja / merma')], db_index=True, default='available', max_length=20)),
                ('destination_sn', models.CharField(blank=True, db_index=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entry', 'Alta'), ('transfer', 'Cambio de ubicación'), ('assign', 'Entrega / instalación'), ('return', 'Devolución'), ('reserve', 'Reserva'), ('scrap', 'Merma'), ('correction', 'Corrección')], max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('destination_sn', models.CharField(blank=True, db_index=True, max_length=160)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='inventory.location')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.item')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='inventory.location')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.technician')),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('bool', 'Sí/No'), ('date', 'Fecha'), ('choice', 'Lista')], default='text', max_length=12)),
                ('required', models.BooleanField(default=False)),
                ('searchable', models.BooleanField(default=True)),
                ('reportable', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='inventory.category')),
            ],
            options={
                'unique_together': {('category', 'key')},
            },
        ),
    ]
