# Generated by Django 5.2.5 on 2026-08-16 11:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('id_header', models.CharField(default='ID Interno', max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(db_index=True, max_length=160)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('assigned', 'Entregado / instalado'), ('scrapped', 'Baja / merma'), ('incident', 'Incidencia')], db_index=True, default='available', max_length=20)),
                ('current_sn', models.CharField(blank=True, db_index=True, max_length=180)),
                ('current_technician', models.CharField(blank=True, db_index=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records_created', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='inventory.inventorytable')),
            ],
            options={
                'ordering': ('table', 'internal_id'),
                'unique_together': {('table', 'internal_id')},
            },
        ),
        migrations.CreateModel(
            name='RecordMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entry', 'Alta / importación'), ('assign', 'Entrega / instalación'), ('return', 'Devolución'), ('scrap', 'Baja / merma'), ('correction', 'Corrección')], max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('technician_name', models.CharField(blank=True, db_index=True, max_length=160)),
                ('destination_sn', models.CharField(blank=True, db_index=True, max_length=180)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_movements', to='inventory.inventoryrecord')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='InventoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('key', models.SlugField(max_length=180)),
                ('position', models.PositiveIntegerField(default=0)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('bool', 'Sí/No')], default='text', max_length=12)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_destination_sn', models.BooleanField(default=False)),
                ('is_technician', models.BooleanField(default=False)),
                ('searchable', models.BooleanField(default=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_fields', to='inventory.inventorytable')),
            ],
            options={
                'ordering': ('position',),
                'unique_together': {('table', 'key')},
            },
        ),
    ]
