# Generated by Django 5.2.5 on 2026-08-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorytable_inventoryrecord_recordmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytable',
            name='id_prefix',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inventorytable',
            name='id_width',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='inventorytable',
            name='next_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
