# Generated by Django 5.2.5 on 2026-08-16 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorytable_id_prefix_inventorytable_id_width_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('assigned', 'Entregado / instalado'), ('scrapped', 'Baja / merma'), ('incident', 'Incidencia')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='recordmovement',
            name='movement_type',
            field=models.CharField(choices=[('entry', 'Alta / importación'), ('reserve', 'Reserva'), ('assign', 'Entrega / instalación'), ('return', 'Devolución'), ('scrap', 'Baja / merma'), ('correction', 'Corrección')], max_length=20),
        ),
        migrations.CreateModel(
            name='LabelPrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=180)),
                ('copies', models.PositiveSmallIntegerField(default=2)),
                ('printer_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('printed', 'Impreso'), ('failed', 'Error')], db_index=True, default='pending', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_print_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('Pintura', 'Pintura'), ('Montaje', 'Montaje'), ('Calidad', 'Calidad'), ('Reparaciones', 'Reparaciones'), ('Auditoria', 'Auditoría'), ('PlanRenove', 'PlanRenove'), ('Direccion', 'Dirección')], max_length=40)),
                ('destination_sn', models.CharField(db_index=True, max_length=180)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('delivered', 'Objeto entregado'), ('cancelled', 'Cancelada'), ('scrapped', 'Merma')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.inventoryrecord')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('record',), name='one_pending_reservation_per_record')],
            },
        ),
    ]
