# Generated by Django 5.2.5 on 2026-08-18 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_gestor_bootstrap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, db_index=True, max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('model_reference', models.CharField(blank=True, max_length=180)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('pending', 'Solicitud pendiente'), ('loaned', 'Prestado'), ('out', 'Fuera de servicio'), ('retired', 'Baja')], db_index=True, default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category', 'name', 'internal_id'),
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-requested_at', '-pk'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='loan',
            name='one_active_loan_per_record',
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='one_pending_reservation_per_record',
        ),
        migrations.AddField(
            model_name='reservation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='inventory.inventoryrecord'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de aceptación'), ('accepted', 'Aceptada'), ('delivered', 'Objeto entregado'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada'), ('scrapped', 'Merma')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('record',), name='one_open_reservation_per_record'),
        ),
        migrations.AddField(
            model_name='loanitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_items_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='inventory.loanitem'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests', to='inventory.loanitem'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='inventory.loanrequest'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('record__isnull', False), ('returned_at__isnull', True)), fields=('record',), name='one_active_legacy_loan_per_record'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('loan_item__isnull', False), ('returned_at__isnull', True)), fields=('loan_item',), name='one_active_loan_per_item'),
        ),
        migrations.AddConstraint(
            model_name='loanrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('item',), name='one_pending_loan_request_per_item'),
        ),
    ]
