# Generated by Django 5.2.5 on 2026-08-18 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_loan_requests_and_reservation_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBatchSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('client', models.CharField(blank=True, db_index=True, max_length=160)),
                ('concept', models.CharField(blank=True, db_index=True, max_length=160)),
                ('position', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_batch_sheets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('client', 'concept', 'position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ClientBatchRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(db_index=True, max_length=160)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=200)),
                ('units_pending', models.PositiveIntegerField(default=0)),
                ('units_stock', models.PositiveIntegerField(default=0)),
                ('units_sent', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('client', models.CharField(blank=True, db_index=True, max_length=160)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_batch_rows_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_batch_rows_updated', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='inventory.clientbatchsheet')),
            ],
            options={
                'ordering': ('sheet', 'internal_id'),
            },
        ),
        migrations.CreateModel(
            name='ClientBatchField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('key', models.SlugField(max_length=180)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('bool', 'Sí/No')], default='text', max_length=12)),
                ('position', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_batch_fields_created', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='inventory.clientbatchsheet')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ClientBatchChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('sheet_created', 'Hoja creada'), ('sheet_modified', 'Hoja modificada'), ('field_created', 'Campo creado'), ('field_modified', 'Campo modificado'), ('field_disabled', 'Campo retirado'), ('row_created', 'Registro creado'), ('row_modified', 'Registro modificado')], db_index=True, max_length=24)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_batch_changes', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='inventory.clientbatchfield')),
                ('row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='inventory.clientbatchrow')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='inventory.clientbatchsheet')),
            ],
            options={
                'ordering': ('-changed_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='clientbatchsheet',
            constraint=models.UniqueConstraint(fields=('client', 'concept', 'name'), name='unique_client_batch_sheet_name'),
        ),
        migrations.AddConstraint(
            model_name='clientbatchrow',
            constraint=models.UniqueConstraint(fields=('sheet', 'internal_id'), name='unique_client_batch_row_id'),
        ),
        migrations.AddConstraint(
            model_name='clientbatchfield',
            constraint=models.UniqueConstraint(fields=('sheet', 'key'), name='unique_client_batch_field_key'),
        ),
    ]
