# Generated by Django 5.2.5 on 2026-08-18 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_clientbatchsheet_clientbatchrow_clientbatchfield_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbatchrow',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name='clientbatchrow',
            name='component',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clientbatchrow',
            name='model_reference',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clientbatchrow',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientbatchsheet',
            name='next_row_number',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='IPBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('banned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('banned_until', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('banned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ip_bans_created', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ip_bans_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-banned_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ServiceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('request_count', models.PositiveBigIntegerField(default=1)),
                ('last_path', models.CharField(blank=True, max_length=500)),
                ('last_user_agent', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen_at', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('ip_address', 'user'), name='unique_service_access_ip_user')],
            },
        ),
    ]
