from django.conf import settings
from django.db import migrations, models
import datetime
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies=[("inventory","0017_security_schedule_full")]

    operations=[
        migrations.AddField(
            model_name="securityaccesspolicy",
            name="updated_by",
            field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="security_policies_updated",to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="securityaccessevent",
            name="previous_ip",
            field=models.GenericIPAddressField(blank=True,null=True),
        ),
        migrations.AddField(
            model_name="securityaccessevent",
            name="previous_data",
            field=models.JSONField(blank=True,default=dict),
        ),
        migrations.AddField(
            model_name="securityaccessevent",
            name="current_data",
            field=models.JSONField(blank=True,default=dict),
        ),
        migrations.AddField(
            model_name="securityaccessevent",
            name="reviewed_at",
            field=models.DateTimeField(blank=True,null=True),
        ),
        migrations.AddField(
            model_name="securityaccessevent",
            name="reviewed_by",
            field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="security_events_reviewed",to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="securityaccessevent",
            name="resolution",
            field=models.CharField(blank=True,max_length=40),
        ),
        migrations.AddField(
            model_name="activesecuritysession",
            name="browser",
            field=models.CharField(blank=True,max_length=120),
        ),
        migrations.AddField(
            model_name="activesecuritysession",
            name="operating_system",
            field=models.CharField(blank=True,max_length=120),
        ),
        migrations.AddField(
            model_name="activesecuritysession",
            name="language",
            field=models.CharField(blank=True,max_length=40),
        ),
        migrations.AddField(
            model_name="activesecuritysession",
            name="timezone_name",
            field=models.CharField(blank=True,max_length=80),
        ),
        migrations.AddField(
            model_name="activesecuritysession",
            name="screen_resolution",
            field=models.CharField(blank=True,max_length=40),
        ),
        migrations.AddField(
            model_name="activesecuritysession",
            name="client_data",
            field=models.JSONField(blank=True,default=dict),
        ),
        migrations.AddField(
            model_name="activesecuritysession",
            name="fingerprint_hash",
            field=models.CharField(blank=True,db_index=True,max_length=64),
        ),
        migrations.AddField(
            model_name="activesecuritysession",
            name="closed_at",
            field=models.DateTimeField(blank=True,null=True),
        ),
        migrations.AlterField(
            model_name="securityaccessevent",
            name="level",
            field=models.CharField(choices=[("YELLOW","Amarilla"),("RED","Roja")],db_index=True,max_length=10),
        ),
        migrations.AlterField(
            model_name="securityaccessevent",
            name="event_type",
            field=models.CharField(choices=[("FINGERPRINT_CHANGED","Cambio de huella"),("MULTIPLE_IP","Múltiples IP simultáneas"),("OUT_OF_SCHEDULE","Acceso fuera de horario"),("AUTO_LOGOUT","Cierre automático por horario")],db_index=True,max_length=50),
        ),
        migrations.AlterField(
            model_name="securityaccessevent",
            name="reviewed",
            field=models.BooleanField(db_index=True,default=False),
        ),
        migrations.AlterField(
            model_name="securityaccesspolicy",
            name="start_time",
            field=models.TimeField(default=datetime.time(8,0)),
        ),
        migrations.AlterField(
            model_name="securityaccesspolicy",
            name="end_time",
            field=models.TimeField(default=datetime.time(18,0)),
        ),
        migrations.AlterField(
            model_name="securityaccessevent",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="security_events",to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="securityaccessevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True,db_index=True),
        ),
        migrations.AlterField(
            model_name="activesecuritysession",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="security_sessions",to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="activesecuritysession",
            name="session_key",
            field=models.CharField(db_index=True,max_length=100),
        ),
        migrations.AlterField(
            model_name="activesecuritysession",
            name="ip",
            field=models.GenericIPAddressField(blank=True,db_index=True,null=True),
        ),
        migrations.AlterField(
            model_name="activesecuritysession",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True,db_index=True),
        ),
        migrations.AlterField(
            model_name="activesecuritysession",
            name="last_activity",
            field=models.DateTimeField(auto_now=True,db_index=True),
        ),
        migrations.AlterField(
            model_name="activesecuritysession",
            name="closed",
            field=models.BooleanField(db_index=True,default=False),
        ),
        migrations.DeleteModel(name="AccessSecurityEvent"),
        migrations.DeleteModel(name="AccessPolicy"),
    ]
