from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

DEFAULTS=[
 ('Pedidos · trazabilidad completa','Unidades, reparaciones, componentes instalados y costes por pedido',"SELECT o.id AS pedido_id,o.name AS pedido,c.name AS cliente,u.serial_number AS sn,r.id AS reparacion_id,r.repair_type AS reparacion,co.reference AS componente,co.price AS precio,ir.username AS tecnico_instalacion,cr.installed_at AS fecha_instalacion FROM inventory_customerorder o JOIN inventory_customer c ON c.id=o.customer_id LEFT JOIN inventory_orderunit u ON u.order_id=o.id LEFT JOIN inventory_componentreservation cr ON cr.unit_id=u.id AND cr.status='installed' LEFT JOIN inventory_repair r ON r.id=cr.repair_id LEFT JOIN inventory_component co ON co.id=cr.component_id LEFT JOIN auth_user ir ON ir.id=cr.installed_by_id ORDER BY o.id,u.serial_number,r.id"),
 ('Unidades · historial','Historial de reservas e instalaciones por unidad',"SELECT u.serial_number AS sn,o.name AS pedido,cr.id AS reserva,co.component_type AS componente,co.reference,co.price,t.username AS reservado_por,cr.reserved_at,i.username AS instalado_por,cr.installed_at,cr.status FROM inventory_orderunit u JOIN inventory_customerorder o ON o.id=u.order_id LEFT JOIN inventory_componentreservation cr ON cr.unit_id=u.id LEFT JOIN inventory_component co ON co.id=cr.component_id LEFT JOIN auth_user t ON t.id=cr.technician_id LEFT JOIN auth_user i ON i.id=cr.installed_by_id ORDER BY u.serial_number,cr.reserved_at"),
 ('Técnicos · intervenciones','Reservas e instalaciones realizadas por técnicos',"SELECT COALESCE(i.username,t.username) AS tecnico,u.serial_number AS sn,o.name AS pedido,co.component_type AS componente,co.price,cr.status,cr.reserved_at,cr.installed_at FROM inventory_componentreservation cr JOIN inventory_orderunit u ON u.id=cr.unit_id JOIN inventory_customerorder o ON o.id=u.order_id JOIN inventory_component co ON co.id=cr.component_id LEFT JOIN auth_user t ON t.id=cr.technician_id LEFT JOIN auth_user i ON i.id=cr.installed_by_id ORDER BY tecnico,o.id,u.serial_number"),
]
def seed(apps,schema_editor):
 Q=apps.get_model('inventory','SavedQuery'); User=apps.get_model(*settings.AUTH_USER_MODEL.split('.')); user=User.objects.filter(is_superuser=True).order_by('id').first()
 if not user: return
 for name,description,sql in DEFAULTS: Q.objects.get_or_create(name=name,defaults={'description':description,'sql':sql,'original_sql':sql,'is_system':True,'created_by':user})
class Migration(migrations.Migration):
 dependencies=[('inventory','0029_order_traceability_redesign'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[migrations.CreateModel(name='SavedQuery',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=180,unique=True)),('description',models.TextField(blank=True)),('sql',models.TextField()),('active',models.BooleanField(db_index=True,default=True)),('is_system',models.BooleanField(db_index=True,default=False)),('original_sql',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('created_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='saved_queries_created',to=settings.AUTH_USER_MODEL))]),migrations.RunPython(seed,migrations.RunPython.noop)]
