#!/usr/bin/env bash
set -Eeuo pipefail
MODE="${1:-}"; APP_ROOT="${PULSIA_APP_ROOT:-/almacen}"; APP_SERVICE="pulsia-inventario"; CADDY_SERVICE="pulsia-inventario-caddy"; STAMP="$(date +%Y%m%d_%H%M%S)"; UPDATE_STARTED=0
info(){ echo "[INFO] $*"; }; ok(){ echo "[OK] $*"; }; warn(){ echo "[AVISO] $*"; }; fail(){ echo "[ERROR] $*" >&2; exit 1; }
[[ "$MODE" == solo-programa || "$MODE" == programa-y-bd || "$MODE" == estructural ]] || fail "Modo de actualización no válido."; [[ ${EUID} -eq 0 ]] || exec sudo -E "$0" "$MODE"
SOURCE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"; [[ -f "$SOURCE_ROOT/manage.py" && -d "$SOURCE_ROOT/inventory" && -d "$SOURCE_ROOT/config" ]] || fail "Paquete PULSIA inválido."
valid_server(){ [[ -d "$1" && -f "$1/manage.py" && -d "$1/inventory" && -d "$1/config" ]]; }; valid_server "$APP_ROOT" || fail "Servidor no encontrado en $APP_ROOT"; APP_ROOT="$(cd "$APP_ROOT" && pwd)"
[[ "$(readlink -f "$SOURCE_ROOT")" != "$(readlink -f "$APP_ROOT")" ]] || { ok "El script pertenece a la instalación; no hay actualización externa."; exit 0; }
command -v rsync >/dev/null || fail "Se necesita rsync."; RSYNC_EXCLUDES=(--exclude='.venv/' --exclude='.env' --exclude='data/' --exclude='backups/' --exclude='logs/' --exclude='certs/' --exclude='.git/' --exclude='__pycache__/' --exclude='*.pyc'); CHANGES="$(rsync -ani --delete "${RSYNC_EXCLUDES[@]}" "$SOURCE_ROOT/" "$APP_ROOT/")"; [[ -n "$CHANGES" ]] || { ok "Ya está actualizado."; exit 0; }
BACKUP_ROOT="$APP_ROOT/backups/actualizaciones"; BACKUP_DIR="$BACKUP_ROOT/$STAMP"; DB_PATH="$APP_ROOT/data/inventario.sqlite3"; ENV_PATH="$APP_ROOT/.env"; CODE_BACKUP="$BACKUP_DIR/codigo_previo.tar.gz"; DB_BACKUP="$BACKUP_DIR/inventario.sqlite3"; ENV_BACKUP="$BACKUP_DIR/.env"
rollback(){ local rc=$?; trap - ERR; echo "[ERROR] Fallo. Restaurando backup..." >&2; if [[ $UPDATE_STARTED -eq 1 && -f "$CODE_BACKUP" ]]; then find "$APP_ROOT" -mindepth 1 -maxdepth 1 ! -name '.venv' ! -name '.env' ! -name data ! -name backups ! -name logs ! -name certs ! -name '.git' -exec rm -rf {} + 2>/dev/null || true; tar -xzf "$CODE_BACKUP" -C "$APP_ROOT" || true; fi; [[ -f "$DB_BACKUP" ]] && cp -a "$DB_BACKUP" "$DB_PATH" || true; [[ -f "$ENV_BACKUP" ]] && cp -a "$ENV_BACKUP" "$ENV_PATH" || true; systemctl restart "$APP_SERVICE" >/dev/null 2>&1 || true; systemctl restart "$CADDY_SERVICE" >/dev/null 2>&1 || true; exit "$rc"; }; trap rollback ERR
mkdir -p "$BACKUP_DIR"; chmod 0700 "$BACKUP_DIR" || true; systemctl stop "$CADDY_SERVICE" 2>/dev/null || true; systemctl stop "$APP_SERVICE" 2>/dev/null || true; tar -czf "$CODE_BACKUP" -C "$APP_ROOT" --exclude='./.venv' --exclude='./.env' --exclude='./data' --exclude='./backups' --exclude='./logs' --exclude='./certs' --exclude='./.git' --exclude='*/__pycache__' --exclude='*.pyc' .; if [[ -f "$DB_PATH" ]]; then command -v sqlite3 >/dev/null 2>&1 && sqlite3 "$DB_PATH" ".backup '$DB_BACKUP'" || cp -a "$DB_PATH" "$DB_BACKUP"; fi; [[ -f "$ENV_PATH" ]] && cp -a "$ENV_PATH" "$ENV_BACKUP"; ln -sfn "$BACKUP_DIR" "$BACKUP_ROOT/ultimo"; UPDATE_STARTED=1
info "Sincronizando código y eliminando archivos obsoletos..."; rsync -a --delete "${RSYNC_EXCLUDES[@]}" "$SOURCE_ROOT/" "$APP_ROOT/"; STALE="$(rsync -ani --delete "${RSYNC_EXCLUDES[@]}" "$SOURCE_ROOT/" "$APP_ROOT/")"; [[ -z "$STALE" ]] || { echo "$STALE"; fail "La instalación conserva diferencias/archivos obsoletos."; }; find "$APP_ROOT/inventory" -type d -name '__pycache__' -prune -exec rm -rf {} + 2>/dev/null || true
APP_USER="$(systemctl show "$APP_SERVICE" -p User --value 2>/dev/null || true)"; [[ -n "$APP_USER" && "$APP_USER" != root ]] || APP_USER="$(stat -c '%U' "$DB_PATH" 2>/dev/null || stat -c '%U' "$APP_ROOT")"; APP_GROUP="$(id -gn "$APP_USER" 2>/dev/null || stat -c '%G' "$APP_ROOT")"; chown -R "$APP_USER:$APP_GROUP" "$APP_ROOT" || true; find "$APP_ROOT/sistema" -type f -name '*.sh' -exec sed -i 's/\r$//' {} + 2>/dev/null || true; find "$APP_ROOT/sistema" -type f -name '*.sh' -exec chmod 0750 {} + 2>/dev/null || true
PYTHON="$APP_ROOT/.venv/bin/python"; PIP="$APP_ROOT/.venv/bin/pip"; [[ -x "$PYTHON" ]] || fail "No existe $PYTHON"; REQ=""; [[ -f "$APP_ROOT/requirements/servidor.txt" ]] && REQ="$APP_ROOT/requirements/servidor.txt"; [[ -z "$REQ" && -f "$APP_ROOT/requirements.txt" ]] && REQ="$APP_ROOT/requirements.txt"; [[ -n "$REQ" && -x "$PIP" ]] && "$PIP" install -r "$REQ"; cd "$APP_ROOT"; if [[ "$MODE" != solo-programa ]]; then "$PYTHON" manage.py migrate --noinput; else "$PYTHON" manage.py showmigrations --plan | grep -q '\[ \]' && warn "Hay migraciones pendientes." || true; fi; "$PYTHON" manage.py check; systemctl daemon-reload; systemctl restart "$APP_SERVICE"; systemctl restart "$CADDY_SERVICE"; systemctl is-active --quiet "$APP_SERVICE" || fail "$APP_SERVICE no está activo"; systemctl is-active --quiet "$CADDY_SERVICE" || fail "$CADDY_SERVICE no está activo"; trap - ERR; ok "Actualización completada correctamente."; echo "Backup: $BACKUP_DIR"